title: greenagile.org
description: A compact operating frame that integrates sustainability empirically into agile software development
theme: just-the-docs

url: https://greenagile.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
