title: Green Agile Guide
description: A compact operating frame that integrates sustainability empirically into agile software development
theme: just-the-docs

url: https://greenagile.org

aux_links:
  View on GitHub: https://github.com/napit-apps/green-agile-guide/

aux_links_new_tab: true

color_scheme: green

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)


# External navigation links
nav_external_links:
  - title: mehr.wert Software und IT Beratung GmbH
    url: https://mehrwert.tech
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false


back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2025 mehr.wert Software und IT Beratung GmbH. <a href="/about">About.</a>'

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red